In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Success")

Success

In [5]:
df = pd.read_csv(r"C:\Users\vasan\apexplanet-data-analytics\data\Superstore.csv")
df.head()

,Order ID,Order Date,Customer Name,Region,Category,Sub-Category,Sales,Profit,Quantity
0,1001,2026-01-05,Alice,East,Furniture,Chairs,250.50,45.2,2
1,1002,2026-01-06,Bob,West,Technology,Phones,899.99,180.0,1
2,1003,2026-01-07,Charlie,South,Office Supplies,Binders,35.75,8.5,5
3,1004,2026-01-08,David,North,Furniture,Tables,450.00,-25.0,1
4,1005,2026-01-09,Eva,East,Technology,Laptops,1200.00,300.0,1

In [7]:
df.head()

,Order ID,Order Date,Customer Name,Region,Category,Sub-Category,Sales,Profit,Quantity
0,1001,2026-01-05,Alice,East,Furniture,Chairs,250.50,45.2,2
1,1002,2026-01-06,Bob,West,Technology,Phones,899.99,180.0,1
2,1003,2026-01-07,Charlie,South,Office Supplies,Binders,35.75,8.5,5
3,1004,2026-01-08,David,North,Furniture,Tables,450.00,-25.0,1
4,1005,2026-01-09,Eva,East,Technology,Laptops,1200.00,300.0,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10 non-null     int64
 1   Order Date     10 non-null     object
 2   Customer Name  10 non-null     object
 3   Region         10 non-null     object
 4   Category       10 non-null     object
 5   Sub-Category   10 non-null     object
 6   Sales          10 non-null     float64
 7   Profit         10 non-null     float64
 8   Quantity       10 non-null     int64
dtypes: float64(2), int64(2), object(5)
memory usage: 852.0+ bytes

In [8]:
df.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Region           0
Category         0
Sub-Category     0
Sales            0
Profit           0
Quantity         0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

         Order ID        Sales      Profit   Quantity
count    10.00000    10.000000   10.000000  10.000000
mean   1005.50000   377.474000   66.790000   3.100000
std       3.02765   406.767249  100.096558   2.766867
min    1001.00000    18.500000  -25.000000   1.000000
25%    1003.25000    80.000000   10.125000   1.250000
50%    1005.50000   200.250000   25.000000   2.000000
75%    1007.75000   562.500000   78.800000   3.750000
max    1010.00000  1200.000000  300.000000  10.000000

In [37]:
df.tail()

,Order ID,Order Date,Customer Name,Region,Category,Sub-Category,Sales,Profit,Quantity
5,1006,2026-01-10,Frank,West,Office Supplies,Paper,18.5,4.2,10
6,1007,2026-01-11,Grace,South,Furniture,Bookcases,600.0,90.0,2
7,1008,2026-01-12,Helen,North,Technology,Accessories,75.0,20.0,3
8,1009,2026-01-13,Ian,East,Office Supplies,Storage,150.0,30.0,4
9,1010,2026-01-14,Jane,West,Furniture,Furnishings,95.0,15.0,2

In [38]:
df.shape

(10, 9)

In [39]:
df.columns

Index(['Order ID', 'Order Date', 'Customer Name', 'Region', 'Category',
       'Sub-Category', 'Sales', 'Profit', 'Quantity'],
      dtype='object')

In [43]:
import os

os.path.exists(r"C:\Users\vasan\apexplanet-data-analytics\data\Superstore.csv")

True

In [45]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!